version: '3.9'
services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: main
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"


    backend:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - .:/app
        ports:
            - "8001:5000"
        depends_on:
            - db